<?php

namespace AdminBundle\Repository;

/**
 * LoginDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
